"""Add description field to Lesson

Revision ID: 461af13a3876
Revises: 2bc0b4104f39
Create Date: 2025-10-06 14:22:17.787894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461af13a3876'
down_revision = '2bc0b4104f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
