"""Add progress columns

Revision ID: 5463e8492da9
Revises: 
Create Date: 2025-09-16 01:26:42.576133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5463e8492da9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hadith_progress', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('arabic_progress', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('arabic_progress')
        batch_op.drop_column('hadith_progress')

    # ### end Alembic commands ###
