"""Add student hub files

Revision ID: 84bccfe32c83
Revises: c6a6402f6866
Create Date: 2025-09-28 08:10:10.790840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84bccfe32c83'
down_revision = 'c6a6402f6866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('hadith_progress')
        batch_op.drop_column('arabic_progress')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arabic_progress', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('hadith_progress', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
