"""Add feedback fields to student hub files

Revision ID: 89128034c301
Revises: 84bccfe32c83
Create Date: 2025-09-28 09:35:00.835666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89128034c301'
down_revision = '84bccfe32c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_hub_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('feedback_grade', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_hub_file', schema=None) as batch_op:
        batch_op.drop_column('feedback_grade')
        batch_op.drop_column('feedback_text')

    # ### end Alembic commands ###
