"""Add show_on_homepage field to Course model

Revision ID: bf62cdc9f90c
Revises: df7cf57082d5
Create Date: 2025-10-03 23:56:52.787813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf62cdc9f90c'
down_revision = 'df7cf57082d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_on_homepage', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('arabic_progress')
        batch_op.drop_column('hadith_progress')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hadith_progress', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('arabic_progress', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('show_on_homepage')

    # ### end Alembic commands ###
