"""empty message

Revision ID: db899b0c2fc1
Revises: 16d4cb3022b3
Create Date: 2025-09-28 11:57:57.097888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db899b0c2fc1'
down_revision = '16d4cb3022b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_retake_attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempt_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_complete', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('question_order_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('current_index', sa.Integer(), nullable=True))
        batch_op.alter_column('lesson_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_retake_attempt', schema=None) as batch_op:
        batch_op.alter_column('lesson_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('current_index')
        batch_op.drop_column('question_order_json')
        batch_op.drop_column('is_complete')
        batch_op.drop_column('attempt_type')

    # ### end Alembic commands ###
