"""Add course hierarchy and monetization support

Revision ID: df7cf57082d5
Revises: ab12ef7890cd
Create Date: 2025-10-01 15:14:59.908453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7cf57082d5'
down_revision = 'ab12ef7890cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('access_type', sa.String(length=20), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_user_course_access')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('order_index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('stripe_product_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('stripe_price_id', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key('fk_course_parent_id', 'course', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint('fk_course_parent_id', type_='foreignkey')
        batch_op.drop_column('stripe_price_id')
        batch_op.drop_column('stripe_product_id')
        batch_op.drop_column('price')
        batch_op.drop_column('is_published')
        batch_op.drop_column('order_index')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('course_type')

    op.drop_table('course_access')
    # ### end Alembic commands ###
